[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "anyquart>=0.1.1",
    "anycorn>=0.11.2",
    "pytest>=9.1.1",
    "anyquart_pydantic>=0.2.0"
]

[tool.pytest.ini_options]
testpaths = ["tests"]
anyio_mode = "auto"

[tool.uv.sources]
anyquart = { path = "../../", editable = true }
